import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Header/NavBar";
import Footer from "@/components/Footer/Footer";
import ExerciseProvider from "@/context/ExerciseContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"

      className={`${geistSans.variable} ${geistMono.variable} bg-black h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ExerciseProvider>
          <NavBar />
          {children}
          <Footer />
        </ExerciseProvider>


      </body>
    </html>
  );
}
